### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by shsjxzh** [kitauji-gwent/kitauji-gwent#6]
"gulp --production" command failed when I try to build locally......

Detail:

[12:50:16] Using gulpfile /mnt/c/wsl_file/myWebserverRoot/kitauji-gwent/gulpfile.js
[12:50:16] Starting 'watch'...
[12:50:16] Finished 'watch' after 122 μs
[12:50:16] Starting 'browserify'...
[12:50:16] Finished 'browserify' after 12 ms
[12:50:16] Starting 'sass'...
[12:50:16] Finished 'sass' after 10 ms
[12:50:16] Starting 'unit tests'...
[12:50:16] Finished 'unit tests' after 2.26 ms
[12:50:16] Starting 'index'...
[12:50:16] Finished 'index' after 1.31 ms
[12:50:16] Starting 'resize sm'...
[12:50:16] Starting 'resize md'...

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Stream yields empty buffer
    at Socket.<anonymous> (/mnt/c/wsl_file/myWebserverRoot/kitauji-gwent/node_modules/gm/lib/command.js:57:17)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! kitauji-gwent@1.0.0 build: `gulp --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kitauji-gwent@1.0.0 build script 'gulp --production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kitauji-gwent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kitauji-gwent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kitauji-gwent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by BrotherJing** [comment]
@shsjxzh node版本太高太低都不行。。 我现在用7.5.0 看下https://github.com/kitauji-gwent/kitauji-gwent/blob/master/.travis.yml
还有别的可能遇到的错误可以看看这里：
https://github.com/exane/not-gwent-online/issues/4

**Comment by hzsydy** [comment]
> @shsjxzh node版本太高太低都不行。。 我现在用7.5.0 看下https://github.com/kitauji-gwent/kitauji-gwent/blob/master/.travis.yml
> 还有别的可能遇到的错误可以看看这里：
> [exane#4](https://github.com/exane/not-gwent-online/issues/4)

这答案棒极了 感觉应该放到readme里...js萌新折腾了俩小时lwip源码最后不得已放弃了2333
毕竟吹学家不一定会js（给吹学家丢人了）
